#!/bin/bash
# Rename ASCII-slug badminton videos in hlv-zheng-siwei/ to proper Vietnamese: "NN - Title.mp4"
# NN = trailing course-order suffix (01-83). Files with prefix "short*" are ignored.
set -euo pipefail
cd "/Users/sonnp/tools/grabber/downloads/hlv-zheng-siwei"
echo "Before (non-short): $(ls | grep -v '^short' | grep -c .) files"

mv "video-3-tra-giao-cau-trong-danh-doi-nang-cao-phan-1_01.mp4" "01 - Trả giao cầu trong đánh đôi nâng cao - Phần 1.mp4"
mv "video-4-tra-giao-cau-trong-danh-doi-nang-cao-phan-2_02.mp4" "02 - Trả giao cầu trong đánh đôi nâng cao - Phần 2.mp4"
mv "video-53-tra-giao-cau-nang-cao-trong-danh-doi-chem-cau-ngang-hong-thuan-tay_03.mp4" "03 - Trả giao cầu nâng cao trong đánh đôi - Chém cầu ngang hông thuận tay.mp4"
mv "video-61-tra-giao-cau-nang-cao-trong-danh-doi-chem-cau-ngang-hong-trai-tay_04.mp4" "04 - Trả giao cầu nâng cao trong đánh đôi - Chém cầu ngang hông trái tay.mp4"
mv "video-68-ky-thuat-tra-giao-cau-nang-cao-an-diem-truc-tiep-cua-cac-cao-thu_05.mp4" "05 - Kỹ thuật trả giao cầu nâng cao ăn điểm trực tiếp của các cao thủ.mp4"
mv "video-57-cach-tra-giao-cau-chuan-muc-khi-doi-thu-giao-cau-vao-vi-tri-so-2-tren-san_06.mp4" "06 - Cách trả giao cầu chuẩn mực khi đối thủ giao cầu vào vị trí số 2 trên sân.mp4"
mv "video-58-ky-thuat-tra-giao-cau-day-ep-nhanh-vao-trung-lo-trong-cau-long-doi_07.mp4" "07 - Kỹ thuật trả giao cầu đẩy ép nhanh vào trung lộ trong cầu lông đôi.mp4"
mv "video-64-danh-doi-nam-nu-thi-nam-nen-tra-giao-cau-the-nao_08.mp4" "08 - Đánh đôi nam nữ thì nam nên trả giao cầu thế nào.mp4"
mv "video-65-danh-doi-nam-nu-thi-nu-nen-tra-giao-cau-the-nao_09.mp4" "09 - Đánh đôi nam nữ thì nữ nên trả giao cầu thế nào.mp4"
mv "video-66-kinh-nghiem-tra-giao-cau-cho-nam-khi-danh-doi-nam-nu_10.mp4" "10 - Kinh nghiệm trả giao cầu cho nam khi đánh đôi nam nữ.mp4"
mv "video-77-zheng-siwei-phan-tich-duong-cau-doi-nam-nu-tai-giai-vdtg-2023_11.mp4" "11 - Zheng Siwei phân tích đường cầu đôi nam nữ tại giải VĐTG 2023.mp4"
mv "video-81-vi-tri-trong-danh-doi-nam-nu-nu-nen-lui-va-phong-thu-the-nao-khi-nam-hat-cau_12.mp4" "12 - Vị trí trong đánh đôi nam nữ - Nữ nên lùi và phòng thủ thế nào khi nam hất cầu.mp4"
mv "video-8-tu-duy-chuyen-tu-thu-sang-cong-giam-luc-phan-cong_13.mp4" "13 - Tư duy chuyển từ thủ sang công - Giảm lực phản công.mp4"
mv "video-15-1-huong-dan-phan-cau-trai-tay-cheo-san_14.mp4" "14 - Hướng dẫn phản cầu trái tay chéo sân.mp4"
mv "video-71-phan-cau-cheo-san-khi-bi-ep-trai-tay-trong-danh-doi_15.mp4" "15 - Phản cầu chéo sân khi bị ép trái tay trong đánh đôi.mp4"
mv "video-62-phong-thu-nang-cao-tach-cheo-san-tu-o-trai-tay-trong-danh-doi_16.mp4" "16 - Phòng thủ nâng cao tách chéo sân từ ô trái tay trong đánh đôi.mp4"
mv "video-60-tu-duy-muon-luc-de-danh-tra-khi-bi-ep-trai-tay-trong-cau-long-doi_17.mp4" "17 - Tư duy mượn lực để đánh trả khi bị ép trái tay trong cầu lông đôi.mp4"
mv "video-73-ky-thuat-tat-cau-trai-tay-danh-chan-cau-trai-tay_18.mp4" "18 - Kỹ thuật tạt cầu trái tay đánh chặn cầu trái tay.mp4"
mv "video-72-ky-thuat-ve-cau-trai-tay-tren-luoi_19.mp4" "19 - Kỹ thuật ve cầu trái tay trên lưới.mp4"
mv "video-51-tat-cau-bi-dong-trai-tay_20.mp4" "20 - Tạt cầu bị động trái tay.mp4"
mv "video-48-danh-cau-trai-tay-tat-chan-day-sau-voi-cung-1-ky-thuat_21.mp4" "21 - Đánh cầu trái tay tạt chân đẩy sâu với cùng 1 kỹ thuật.mp4"
mv "video-47-keo-luoi-trai-tay-mp4_22.mp4" "22 - Kéo lưới trái tay.mp4"
mv "video-46-keo-luoi-thuan-tay_23.mp4" "23 - Kéo lưới thuận tay.mp4"
mv "video-21-sua-loi-ep-cau-thuan-tay-tren-luoi-thuc-chien_24.mp4" "24 - Sửa lỗi ép cầu thuận tay trên lưới - Thực chiến.mp4"
mv "video-23-huong-dan-bat-cau-thuan-tay-tren-luoi-phan-2_25.mp4" "25 - Hướng dẫn bắt cầu thuận tay trên lưới - Phần 2.mp4"
mv "video-63-bai-tap-nang-cao-kha-nang-danh-chan-danh-tat-cau-tren-luoi_26.mp4" "26 - Bài tập nâng cao khả năng đánh chặn đánh tạt cầu trên lưới.mp4"
mv "video-67-kinh-nghiem-chan-cau-tat-cau-tren-luoi-cua-zheng-siwei_27.mp4" "27 - Kinh nghiệm chặn cầu tạt cầu trên lưới của Zheng Siwei.mp4"
mv "video-74-tu-duy-chan-luoi-trung-tien-san-va-khai-niem-nhip-sau-co-the-kiem-soat_28.mp4" "28 - Tư duy chặn lưới trung tiền sân và khái niệm nhịp sau có thể kiểm soát.mp4"
mv "video-76-cach-chup-luoi-chop-nhoang-cua-vdv-chuyen-nghiep_29.mp4" "29 - Cách chụp lưới chớp nhoáng của VĐV chuyên nghiệp.mp4"
mv "video-40-ky-thuat-moc-cau-thuan-tay-cheo-san_30.mp4" "30 - Kỹ thuật móc cầu thuận tay chéo sân.mp4"
mv "video-37-ky-thuat-chem-cau-thuan-tay_31.mp4" "31 - Kỹ thuật chém cầu thuận tay.mp4"
mv "video-75-cach-tang-luc-cho-cu-tat-cau-thuan-tay-tu-giua-san_32.mp4" "32 - Cách tăng lực cho cú tạt cầu thuận tay từ giữa sân.mp4"
mv "video-27-ky-thuat-phong-thu-trong-danh-doi-phan-3-nang-cao_33.mp4" "33 - Kỹ thuật phòng thủ trong đánh đôi - Phần 3 nâng cao.mp4"
mv "video-44-cach-phong-thu-de-thoat-khoi-the-bi-ep-cau_34.mp4" "34 - Cách phòng thủ để thoát khỏi thế bị ép cầu.mp4"
mv "video-30-thu-tach-cau-cheo-san-trong-danh-doi_35.mp4" "35 - Thủ tách cầu chéo sân trong đánh đôi.mp4"
mv "video-41-bo-phap-lui-danh-cau-bi-dong-cuoi-san_36.mp4" "36 - Bộ pháp lùi đánh cầu bị động cuối sân.mp4"
mv "video-42-bo-phap-danh-don-tach-chan-dung-nhip-trong-tam-thap-tap-chung-theo-trai-cau_37.mp4" "37 - Bộ pháp đánh đơn tách chân đúng nhịp, trọng tâm thấp, tập trung theo trái cầu.mp4"
mv "video-54-danh-lay-the-chu-dong-ngay-sau-khi-vua-giao-cau-xong-bi-quyet-danh-doi_38.mp4" "38 - Đánh lấy thế chủ động ngay sau khi vừa giao cầu xong - Bí quyết đánh đôi.mp4"
mv "video-55-bo-phap-va-ky-thuat-danh-cau-bi-dong-goc-phai-tay-cuoi-san_39.mp4" "39 - Bộ pháp và kỹ thuật đánh cầu bị động góc phải tay cuối sân.mp4"
mv "video-56-bi-quyet-pha-vo-hang-thu-chac-chan-cua-doi-phuong-cau-long-doi_40.mp4" "40 - Bí quyết phá vỡ hàng thủ chắc chắn của đối phương - Cầu lông đôi.mp4"
mv "video-59-cach-hoa-giai-khi-bi-ep-thang-vao-nguoi-sau-khi-dong-doi-vua-giao-cau-xong_41.mp4" "41 - Cách hóa giải khi bị ép thẳng vào người sau khi đồng đội vừa giao cầu xong.mp4"
mv "video-69-than-long-vay-duoi-ky-thuat-cau-long-dinh-cao-cua-zheng-siwei_42.mp4" "42 - Thần long vẫy đuôi - Kỹ thuật cầu lông đỉnh cao của Zheng Siwei.mp4"
mv "video-70-ky-thuat-phong-cau-lua-nhip-an-diem-truc-tiep_43.mp4" "43 - Kỹ thuật phông cầu lừa nhịp ăn điểm trực tiếp.mp4"
mv "video-79-zheng-siwei-phan-tich-tinh-huong-tran-dau-voi-watanabe-tai-giai-vdtg-2022_44.mp4" "44 - Zheng Siwei phân tích tình huống trận đấu với Watanabe tại giải VĐTG 2022.mp4"
mv "video-80-bo-phap-de-danh-tra-cau-phong-lao-va-huong-danh-tra-toi-uu_45.mp4" "45 - Bộ pháp để đánh trả cầu phóng lao và hướng đánh trả tối ưu.mp4"
mv "video-1-tra-giao-cau-trong-doi-nam-va-doi-nam-nu-2_46.mp4" "46 - Trả giao cầu trong đôi nam và đôi nam nữ.mp4"
mv "video-2-tra-giao-cau-trong-danh-doi-phu-hop-cho-nguoi-moi-2_47.mp4" "47 - Trả giao cầu trong đánh đôi phù hợp cho người mới.mp4"
mv "video-5-thuc-chien-tra-giao-cau-trong-danh-doi-2_48.mp4" "48 - Thực chiến trả giao cầu trong đánh đôi.mp4"
mv "video-6-do-giao-cau-cao-sau-cuoi-san-trong-danh-doi-2_49.mp4" "49 - Đỡ giao cầu cao sâu cuối sân trong đánh đôi.mp4"
mv "video-7-chuyen-tu-thu-sang-cong-trong-danh-doi-xoay-vong-phan-cong-2_50.mp4" "50 - Chuyển từ thủ sang công trong đánh đôi - Xoay vòng phản công.mp4"
mv "video-9-xoay-nguoi-dap-cau-bang-ca-canh-tay-2_51.mp4" "51 - Xoay người đập cầu bằng cả cánh tay.mp4"
mv "video-10-sua-loi-dap-cau-khong-cam-cho-fans-2_52.mp4" "52 - Sửa lỗi đập cầu không cắm cho fans.mp4"
mv "video-11-sua-loi-nhay-dap-cau-bang-2-chan-jump-smash-cho-fans-2_53.mp4" "53 - Sửa lỗi nhảy đập cầu bằng 2 chân (jump smash) cho fans.mp4"
mv "video-12-bai-tap-bo-tro-dap-cau-cua-zheng-siwei-2_54.mp4" "54 - Bài tập bổ trợ đập cầu của Zheng Siwei.mp4"
mv "video-13-di-chuyen-tan-cong-lien-hoan-trong-danh-doi-2_55.mp4" "55 - Di chuyển tấn công liên hoàn trong đánh đôi.mp4"
mv "video-14-danh-doi-gap-doi-thu-chem-cau-tot-phai-lam-sao-2_56.mp4" "56 - Đánh đôi gặp đối thủ chém cầu tốt phải làm sao.mp4"
mv "video-14-1-dung-gan-luoi-neu-bi-phong-ve-sau-thi-phai-lam-sao-2_57.mp4" "57 - Đứng gần lưới nếu bị phông về sau thì phải làm sao.mp4"
mv "video-15-bi-ep-trai-tay-sau-khi-dong-doi-giao-cau-phai-lam-sao-2_58.mp4" "58 - Bị ép trái tay sau khi đồng đội giao cầu phải làm sao.mp4"
mv "video-16-cac-duong-phong-thu-da-dang-trong-danh-doi-o-o-thuan-tay-2_59.mp4" "59 - Các đường phòng thủ đa dạng trong đánh đôi ở ô thuận tay.mp4"
mv "video-17-phan-cong-vi-tri-va-nhiem-vu-trong-danh-doi-nam-nu-phan-1-2_60.mp4" "60 - Phân công vị trí và nhiệm vụ trong đánh đôi nam nữ - Phần 1.mp4"
mv "video-18-phan-cong-vi-tri-va-nhiem-vu-trong-danh-doi-nam-nu-phan-2-2_61.mp4" "61 - Phân công vị trí và nhiệm vụ trong đánh đôi nam nữ - Phần 2.mp4"
mv "video-19-loi-thuong-gap-khi-ep-cau-thuan-tay-tren-luoi-phan-1-2_62.mp4" "62 - Lỗi thường gặp khi ép cầu thuận tay trên lưới - Phần 1.mp4"
mv "video-20-loi-thuong-gap-khi-ep-cau-thuan-tay-tren-luoi-phan-2-2_63.mp4" "63 - Lỗi thường gặp khi ép cầu thuận tay trên lưới - Phần 2.mp4"
mv "video-22-huong-dan-ep-cau-thuan-tay-tren-luoi-phan-1-2_64.mp4" "64 - Hướng dẫn ép cầu thuận tay trên lưới - Phần 1.mp4"
mv "video-24-phan-tat-ngang-ca-thuan-tay-va-trai-tay-chi-voi-1-cach-cam-vot-2_65.mp4" "65 - Phản tạt ngang cả thuận tay và trái tay chỉ với 1 cách cầm vợt.mp4"
mv "video-25-ky-thuat-phong-thu-trong-danh-doi-phan-1-2_66.mp4" "66 - Kỹ thuật phòng thủ trong đánh đôi - Phần 1.mp4"
mv "video-26-ky-thuat-phong-thu-trong-danh-doi-phan-2-2_67.mp4" "67 - Kỹ thuật phòng thủ trong đánh đôi - Phần 2.mp4"
mv "video-28-bi-quyet-giu-the-chu-dong-trong-danh-doi-2_68.mp4" "68 - Bí quyết giữ thế chủ động trong đánh đôi.mp4"
mv "video-29-di-chuyen-tan-cong-dot-kich-thuan-tay-2_69.mp4" "69 - Di chuyển tấn công đột kích thuận tay.mp4"
mv "video-31-chuyen-doi-cach-cam-vot-thuan-tay-va-trai-tay-2_70.mp4" "70 - Chuyển đổi cách cầm vợt thuận tay và trái tay.mp4"
mv "video-32-hat-cau-thuan-tay-2_71.mp4" "71 - Hất cầu thuận tay.mp4"
mv "video-33-hat-cau-trai-tay-2_72.mp4" "72 - Hất cầu trái tay.mp4"
mv "video-34-ky-thuat-tat-cau-thuan-tay-2_73.mp4" "73 - Kỹ thuật tạt cầu thuận tay.mp4"
mv "video-35-cach-cam-vot-ve-cau-danh-cau-trai-tay-bi-dong-2_74.mp4" "74 - Cách cầm vợt ve cầu đánh cầu trái tay bị động.mp4"
mv "video-36-3-bai-tap-kich-hoat-chan-truoc-tran-dau-cua-zheng-siwei-2_75.mp4" "75 - 3 bài tập kích hoạt chân trước trận đấu của Zheng Siwei.mp4"
mv "video-38-vi-tri-phong-thu-sau-khi-hat-cau-cheo-san-trong-danh-doi-2_76.mp4" "76 - Vị trí phòng thủ sau khi hất cầu chéo sân trong đánh đôi.mp4"
mv "video-39-tu-the-dung-phong-thu-trong-danh-doi-2_77.mp4" "77 - Tư thế đứng phòng thủ trong đánh đôi.mp4"
mv "video-43-ky-thuat-day-cau-trai-tay-cheo-san-2_78.mp4" "78 - Kỹ thuật đẩy cầu trái tay chéo sân.mp4"
mv "video-45-ky-thuat-bat-luoi-kieu-miet-cau-2_79.mp4" "79 - Kỹ thuật bắt lưới kiểu miết cầu.mp4"
mv "video-49-3-bai-tap-cai-thien-buoc-tach-chan-nhanh-nhu-chop-2_80.mp4" "80 - 3 bài tập cải thiện bước tách chân nhanh như chớp.mp4"
mv "video-50-gian-co-sau-tap-luyen-thi-dau-de-phuc-hoi-va-phong-tranh-chan-thuong-2_81.mp4" "81 - Giãn cơ sau tập luyện thi đấu để phục hồi và phòng tránh chấn thương.mp4"
mv "video-52-bo-phap-di-chuyen-tu-goc-trai-tay-tren-luoi-ve-goc-thuan-tay-cuoi-san-cau-long-don-2_82.mp4" "82 - Bộ pháp di chuyển từ góc trái tay trên lưới về góc thuận tay cuối sân - Cầu lông đơn.mp4"
mv "video-78-nguyen-nhan-va-giai-phap-phuc-hoi-2-loai-chan-thuong-goi-thuong-gap-o-nguoi-choi-cau-long-2_83.mp4" "83 - Nguyên nhân và giải pháp phục hồi 2 loại chấn thương gối thường gặp ở người chơi cầu lông.mp4"

echo "After (NN -): $(ls '0'*' - '*.mp4 '1'*' - '*.mp4 '2'*' - '*.mp4 '3'*' - '*.mp4 '4'*' - '*.mp4 '5'*' - '*.mp4 '6'*' - '*.mp4 '7'*' - '*.mp4 '8'*' - '*.mp4 2>/dev/null | wc -l | tr -d ' ')"
echo "Leftover slugs: $(ls video-* 2>/dev/null | wc -l | tr -d ' ')"