#!/bin/bash
# Rename ASCII-slug badminton videos in ton-hao-bang/ to proper Vietnamese: "NN - Title.mp4"
set -euo pipefail
cd "/Users/sonnp/tools/grabber/downloads/hlv-luu-huy-ton-hao-bang/ton-hao-bang"
echo "Before: $(ls -1 *.mp4 | wc -l | tr -d ' ') files"

mv "video-1-goc-van-xoan-co-tay-toi-uu-nhat-cho-viec-phat-luc-danh-cau.mp4" "01 - Góc vặn xoắn cổ tay tối ưu nhất cho việc phát lực đánh cầu.mp4"
mv "video-2-bi-quyet-dap-cau-manh-va-cam-tu-a-z.mp4" "02 - Bí quyết đập cầu mạnh và cắm từ A-Z.mp4"
mv "video-3-thay-doi-hoan-toan-chat-luong-giao-cau-doi-cua-ban-chi-voi-mot-chi-tiet-nho.mp4" "03 - Thay đổi hoàn toàn chất lượng giao cầu đôi của bạn chỉ với một chi tiết nhỏ.mp4"
mv "video-4-sua-lai-cach-cam-vot-va-xoay-trong-chuan-ky-thuat-de-phat-luc-tot-hon.mp4" "04 - Sửa lại cách cầm vợt và xoay trong chuẩn kỹ thuật để phát lực tốt hơn.mp4"
mv "video-5-kien-thuc-pho-thong-tren-mang-co-the-la-thu-dang-can-tro-ban-len-trinh.mp4" "05 - Kiến thức phổ thông trên mạng có thể là thứ đang cản trở bạn lên trình.mp4"
mv "video-6-phuong-phap-luyen-tap-ve-cau-bi-dong-sat-luoi.mp4" "06 - Phương pháp luyện tập ve cầu bị động sát lưới.mp4"
mv "video-7-tips-kiem-soat-giao-cau-sat-luoi-on-dinh-trong-danh-doi.mp4" "07 - Tips kiểm soát giao cầu sát lưới ổn định trong đánh đôi.mp4"
mv "video-8-cach-mo-vai-chuan-ky-thuat-de-phat-luc-tot-nhat.mp4" "08 - Cách mở vai chuẩn kỹ thuật để phát lực tốt nhất.mp4"
mv "video-9-diem-mau-chot-de-cai-thien-kha-nang-phat-luc-tong-the.mp4" "09 - Điểm mấu chốt để cải thiện khả năng phát lực tổng thể.mp4"
mv "video-10-y-thuc-theo-cau-trong-danh-doi-nhat-dinh-phai-nam-vung.mp4" "10 - Ý thức theo cầu trong đánh đôi nhất định phải nắm vững.mp4"
mv "video-11-cach-di-chuyen-tro-ve-sau-khi-danh-cau-trong-danh-don.mp4" "11 - Cách di chuyển trở về sau khi đánh cầu trong đánh đơn.mp4"
mv "video-12-cac-duong-danh-trai-tay-co-ban-phai-tap-ngay.mp4" "12 - Các đường đánh trái tay cơ bản phải tập ngay.mp4"
mv "video-13-cach-luan-chuyen-vi-tri-trong-danh-doi-cua-vdv-chuyen-nghiep.mp4" "13 - Cách luân chuyển vị trí trong đánh đôi của VĐV chuyên nghiệp.mp4"
mv "video-14-ve-cau-trai-tay-doc-bien-va-cheo-san-chuyen-tiep-trai-tay.mp4" "14 - Ve cầu trái tay dọc biên và chéo sân chuyển tiếp trái tay.mp4"
mv "video-15-bi-quyet-dut-diem-cheo-dau-nhanh-va-bat-ngo.mp4" "15 - Bí quyết dứt điểm chéo đầu nhanh và bất ngờ.mp4"
mv "video-16-sua-loi-vung-ca-canh-tay-khi-danh-cau.mp4" "16 - Sửa lỗi vung cả cánh tay khi đánh cầu.mp4"
mv "video-17-neu-bi-dau-co-tay-hoac-khuyu-tay-thi-co-the-ban-dang-cam-vot-sai.mp4" "17 - Nếu bị đau cổ tay hoặc khuỷu tay thì có thể bạn đang cầm vợt sai.mp4"
mv "video-18-cam-nhan-cach-phat-luc-dung-khi-phong-va-dap-cau.mp4" "18 - Cảm nhận cách phát lực đúng khi phông và đập cầu.mp4"
mv "video-19-khung-phat-luc-chuan-khi-danh-cau-thuan-tay.mp4" "19 - Khung phát lực chuẩn khi đánh cầu thuận tay.mp4"
mv "video-20-ky-thuat-dap-chem-cau-cheo-san.mp4" "20 - Kỹ thuật đập chém cầu chéo sân.mp4"
mv "video-21-chi-4-buoc-de-hoan-thien-ky-thuat-danh-cau-thuan-tay.mp4" "21 - Chỉ 4 bước để hoàn thiện kỹ thuật đánh cầu thuận tay.mp4"
mv "video-22-sua-lai-ky-thuat-danh-cau-thuan-tay-cho-fans.mp4" "22 - Sửa lại kỹ thuật đánh cầu thuận tay cho fans.mp4"
mv "video-23-dung-gap-ep-co-tay-ky-thuat-phat-luc-cua-ban-bi-sai-roi.mp4" "23 - Đừng gập ép cổ tay, kỹ thuật phát lực của bạn bị sai rồi.mp4"
mv "video-24-huong-dan-dap-cau-cam-va-toi-uu-phat-luc.mp4" "24 - Hướng dẫn đập cầu cắm và tối ưu phát lực.mp4"
mv "video-25-dung-qua-tap-chung-vao-ky-thuat-hay-cam-nhan-cam-giac-cau.mp4" "25 - Đừng quá tập trung vào kỹ thuật, hãy cảm nhận cảm giác cầu.mp4"
mv "video-26-huong-dan-giao-cau-chinh-xac-va-on-dinh-nhu-vdv-chuyen-nghiep.mp4" "26 - Hướng dẫn giao cầu chính xác và ổn định như VĐV chuyên nghiệp.mp4"
mv "video-27-4-loi-khien-ban-danh-cau-khong-cam-va-thieu-luc.mp4" "27 - 4 lỗi khiến bạn đánh cầu không cắm và thiếu lực.mp4"
mv "video-28-vai-dieu-can-luu-y-ve-bo-phap-di-chuyen-cau-long.mp4" "28 - Vài điều cần lưu ý về bộ pháp di chuyển cầu lông.mp4"
mv "video-29-phong-thu-va-phan-tat-trong-danh-doi-can-luu-y.mp4" "29 - Phòng thủ và phản tạt trong đánh đôi cần lưu ý.mp4"
mv "video-30-ket-hop-tay-va-nua-than-ben-khong-thuan-de-toi-uu-viec-phat-luc-khi-dap-cau.mp4" "30 - Kết hợp tay và nửa thân bên không thuận để tối ưu việc phát lực khi đập cầu.mp4"
mv "video-31-huong-dan-bat-doi-chan-dap-cau-nhu-vdv-chuyen-nghiep.mp4" "31 - Hướng dẫn bật đổi chân đập cầu như VĐV chuyên nghiệp.mp4"
mv "video-32-lam-the-nao-de-dan-vot-mot-cach-tu-nhien-de-toi-uu-viec-phat-luc-khi-danh-cau.mp4" "32 - Làm thế nào để dẫn vợt một cách tự nhiên để tối ưu việc phát lực khi đánh cầu.mp4"
mv "video-33-kiem-soat-co-tay-va-khuyu-tay-de-co-nhung-pha-dap-cau-manh-va-cam.mp4" "33 - Kiểm soát cổ tay và khuỷu tay để có những pha đập cầu mạnh và cắm.mp4"
mv "video-34-thoi-diem-phat-luc-ly-tuong-khi-thuc-hien-dong-tac-ky-thuat-cau-long.mp4" "34 - Thời điểm phát lực lý tưởng khi thực hiện động tác kỹ thuật cầu lông.mp4"
mv "video-35-ky-thuat-va-bo-phap-bat-luoi-nhanh-va-chu-dong-trong-cau-long.mp4" "35 - Kỹ thuật và bộ pháp bắt lưới nhanh và chủ động trong cầu lông.mp4"
mv "video-36-dap-cau-2-ben-khong-xoay-nguoi.mp4" "36 - Đập cầu 2 bên không xoay người.mp4"
mv "video-37-su-dung-phan-co-core-nhu-the-nao-de-dap-cau-manh-hon.mp4" "37 - Sử dụng phần cơ core như thế nào để đập cầu mạnh hơn.mp4"
mv "video-38-ky-thuat-thu-cau-cao-sau-trong-danh-doi.mp4" "38 - Kỹ thuật thủ cầu cao sâu trong đánh đôi.mp4"
mv "video-39-cach-ke-cau-tren-luoi-sao-cho-on-dinh-va-it-loi.mp4" "39 - Cách kê cầu trên lưới sao cho ổn định và ít lỗi.mp4"
mv "video-40-huong-dan-de-tat-cau-trai-tay-cam-va-manh.mp4" "40 - Hướng dẫn để tạt cầu trái tay cắm và mạnh.mp4"
mv "video-41-sua-lai-cach-cam-vot-thuan-tay-dung-ky-thuat-trong-cau-long.mp4" "41 - Sửa lại cách cầm vợt thuận tay đúng kỹ thuật trong cầu lông.mp4"
mv "video-42-huong-dan-chem-xoa-cau-nhu-vdv-chuyen-nghiep.mp4" "42 - Hướng dẫn chém xoa cầu như VĐV chuyên nghiệp.mp4"

echo "After: $(ls -1 *.mp4 | wc -l | tr -d ' ') files"
echo "Leftover slugs: $(ls video-* 2>/dev/null | wc -l | tr -d ' ')"
